import HydrateRoomHeader from '@/components/hydrate/HydrateRoomHeader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RoomLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="flex flex-col flex-1">{children}</div>;
}
