import RoomHeader from '@/components/RoomHeader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RoomLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-1 flex-col">
      <RoomHeader />
      <div className="flex flex-1">{children}</div>
      <div>2</div>
    </div>
  );
}
