import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth antialiased">
      <body className="bg-bg_page text-text1 min-h-screen font-pretendard overflow-y-auto">
        {children}
      </body>
    </html>
  );
}
