import Providers from '@/components/Providers';
import HydrateLeftNav from '@/components/hydrate/HydrateLeftNav';
import HydrateRoot from '@/components/hydrate/HydrateRoot';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth antialiased h-full">
      <body className="bg-bg_page text-text1 h-full font-pretendard font-medium overflow-hidden">
        <Providers>
          <HydrateRoot>
            <div className="app flex h-full">
              <HydrateLeftNav />
              {children}
            </div>
          </HydrateRoot>
        </Providers>
      </body>
    </html>
  );
}
