import Providers from '@/components/Providers';
import HydrateLeftNav from '@/components/hydrate/HydrateLeftNav';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth antialiased min-h-screen">
      <body className="bg-bg_page text-text1 min-h-screen font-pretendard font-medium overflow-y-auto">
        <Providers>
          <div className="app flex min-h-screen">
            <HydrateLeftNav />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
